using System;
using System.Data;
using System.Threading;
using System.Windows;
using System.Windows.Controls;
using Practical.Data.DataSetTableAdapters;

using DataSet = Practical.Data.DataSet;

namespace Practical.TablesPage
{
    public partial class GroupPage : Page
    {
        private int selectRow = -1;
                
        public GroupPage()
        {
            InitializeComponent();
            update();
            Data.AutoGeneratedColumns += CollapsedColumns;
        }
        
        private void update()
        {
            NameTextBox.Text = "";
            FacultyComboBox.Text = "";
            GroupViewTableAdapter g = new GroupViewTableAdapter();
            DataSet.GroupViewDataTable table = new DataSet.GroupViewDataTable();

            g.Fill(table);
            Data.ItemsSource = table;
            Data.SelectedIndex = selectRow < Data.Items.Count ? selectRow : -1;
            Buttons.selectItem(selectRow > -1 && selectRow < Data.Items.Count);
        }

        private void CollapsedColumns(object sender, EventArgs eventArgs)
        {
            Data.Columns[2].Visibility = Visibility.Collapsed;
        }

        private void ClickAdd(object sender)
        {
            try
            {
                if (this.IsFillArea())
                {
                    new groupTableAdapter().Insert(NameTextBox.Text, Convert.ToInt32(FacultyComboBox.SelectedValue));
                    update();
                }
                else
                {
                    this.showError("Заполнены не все поля");
                }
            }
            catch (Exception exception)
            {
                this.showError("Данный строка уже существует");
            }
        }

        private void ClickChange(object sender)
        {
            try
            {
                if (this.IsFillArea())
                {
                    var items = (Data.SelectedItem as DataRowView).Row;
                    new groupTableAdapter().Update(NameTextBox.Text, Convert.ToInt32(FacultyComboBox.SelectedValue), Convert.ToInt32(items.ItemArray[0]), (Data.SelectedItem as DataRowView).Row.ItemArray[1].ToString(),Convert.ToInt32(items.ItemArray[2]));
                    update();
                }
                else
                {
                    this.showError("Заполнены не все поля");
                }
            }
            catch (Exception exception)
            {
                // ignored
            }
        }

        private void ClickDelete(object sender)
        {
            try
            {
                new groupTableAdapter().Delete(Convert.ToInt32((Data.SelectedItem as DataRowView).Row.ItemArray[0]), (Data.SelectedItem as DataRowView).Row.ItemArray[1].ToString(), Convert.ToInt32((Data.SelectedItem as DataRowView).Row.ItemArray[2]));
                Buttons.selectItem(false);
                update();
            }
            catch (Exception exception)
            {
                this.showError("Нельзя удалить строчку");
            }

        }
        
        private void ClickCancel(object sender)
        {
            NameTextBox.Text = "";
            FacultyComboBox.Text = "";
            this.selectRow = -1;
            Data.SelectedIndex = -1;
            Buttons.selectItem(false);
        }

        private void Doljnost_OnSelectionChanged(object sender, SelectionChangedEventArgs e)
        {
            if (Data.SelectedIndex > -1 && Data.SelectedIndex < Data.Items.Count)
            {
                selectRow = Data.SelectedIndex;
                var items = (Data.SelectedItem as DataRowView).Row;
                NameTextBox.Text = items.ItemArray[1].ToString();
                FacultyComboBox.SelectedValue = items.ItemArray[2];
                Buttons.selectItem(true);
            }
        }

        private void showError(string text)
        {
            MessageBox.Show(text);
        }

        private bool IsFillArea()
        {
            return Methods.IsGoodString(NameTextBox.Text) && Methods.IsGoodString(FacultyComboBox.Text);
        }
    }
}