using System;
using System.Data;
using System.Windows;
using System.Windows.Controls;
using Practical.ComboBox;
using Practical.Data.DataSetTableAdapters;

using DataSet = Practical.Data.DataSet;

namespace Practical.TablesPage
{
    public partial class MarksPage : Page
    {
        private int selectRow = -1;
        
        public MarksPage()
        {
            InitializeComponent();
            update();
            Data.AutoGeneratedColumns += CollapsedColumns;
        }
        
        private void update()
        {
            MarkTextBox.Text = "";
            FacultyComboBox.Text = "";
            LessonComboBox.Text = "";
            Date.Text = "";
            LastDate = "";
            DateCheckBox.IsChecked = false;
            MarksViewTableAdapter g = new MarksViewTableAdapter();
            DataSet.MarksViewDataTable table = new DataSet.MarksViewDataTable();

            g.Fill(table);
            Data.ItemsSource = table;
            Data.SelectedIndex = selectRow < Data.Items.Count ? selectRow : -1;
            Buttons.selectItem(selectRow > -1 && selectRow < Data.Items.Count);
        }
        
        private void CollapsedColumns(object sender, EventArgs eventArgs)
        {
            Data.Columns[2].Visibility = Visibility.Collapsed;
            Data.Columns[3].Visibility = Visibility.Collapsed;
        }

        private void ClickAdd(object sender)
        {
            if (!IsNumberGood())
            {
                this.showError("Указан неверный тип данных");
            }
            else if (this.IsFillArea())
            {
                new marksTableAdapter().Insert(Convert.ToInt32(MarkTextBox.Text), Convert.ToInt32(FacultyComboBox.SelectedValue), Convert.ToInt32(LessonComboBox.SelectedValue), Date.Text.ToString());
                update();
            }
            else
            {
                this.showError("Заполнены не все поля");
            }
        }

        private void ClickChange(object sender)
        {
            if (!IsNumberGood())
            {
                this.showError("Указан неверный тип данных");
            }
            else if (this.IsFillArea())
            {
                var items = (Data.SelectedItem as DataRowView).Row;
                new marksTableAdapter().Update(Convert.ToInt32(MarkTextBox.Text), Convert.ToInt32(FacultyComboBox.SelectedValue), Convert.ToInt32(LessonComboBox.SelectedValue), Date.Text.ToString(), Convert.ToInt32(items.ItemArray[0]), Convert.ToInt32(items.ItemArray[1]), Convert.ToInt32(items.ItemArray[2]), Convert.ToInt32(items.ItemArray[3]));
                update();
            }
            else
            {
                this.showError("Заполнены не все поля");
            }
        }

        private void ClickDelete(object sender)
        {
            try
            {
                new marksTableAdapter().Delete(Convert.ToInt32((Data.SelectedItem as DataRowView).Row.ItemArray[0]), Convert.ToInt32((Data.SelectedItem as DataRowView).Row.ItemArray[1]) , Convert.ToInt32((Data.SelectedItem as DataRowView).Row.ItemArray[2]), Convert.ToInt32((Data.SelectedItem as DataRowView).Row.ItemArray[3]));
                Buttons.selectItem(false);
                update();
            }
            catch (Exception exception)
            {
                this.showError("Нельзя удалить строчку");
            }

        }
        
        private void ClickCancel(object sender)
        {
            MarkTextBox.Text = "";
            FacultyComboBox.Text = "";
            LessonComboBox.Text = "";
            Date.Text = "";
            LastDate = "";
            DateCheckBox.IsChecked = false;
            this.selectRow = -1;
            Data.SelectedIndex = -1;
            Buttons.selectItem(false);
        }

        private void Doljnost_OnSelectionChanged(object sender, SelectionChangedEventArgs e)
        {
            if (Data.SelectedIndex > -1 && Data.SelectedIndex < Data.Items.Count)
            {
                LastDate = "";
                DateCheckBox.IsChecked = false;
                selectRow = Data.SelectedIndex;
                var items = (Data.SelectedItem as DataRowView).Row;
                MarkTextBox.Text = items.ItemArray[1].ToString();
                FacultyComboBox.SelectedValue = items.ItemArray[2];
                LessonComboBox.SelectedValue = items.ItemArray[3];
                Date.Text = items.ItemArray[4].ToString();
                Buttons.selectItem(true);
            }
        }

        private string LastDate;
        private void DateCheckBox_OnChecked(object sender, RoutedEventArgs e)
        {
            Date.IsEnabled = false;
            LastDate = Date.Text;
            Date.SelectedDate = DateTime.Now;
        }
        
        private void DateCheckBox_OnUnchecked(object sender, RoutedEventArgs e)
        {
            Date.IsEnabled = true;
            Date.Text = LastDate;
        }
        
        private void showError(string text)
        {
            MessageBox.Show(text);
        }

        private bool IsFillArea()
        {
            return Methods.IsGoodString(MarkTextBox.Text) && Methods.IsGoodString(FacultyComboBox.Text);
        }

        private bool IsNumberGood()
        {
            return Methods.IsGoodInt(MarkTextBox.Text, 2, 5);
        }
    }
}