using System;
using System.Data;
using System.Windows;
using System.Windows.Controls;
using Practical.Data.DataSetTableAdapters;

using DataSet = Practical.Data.DataSet;

namespace Practical.TablesPage
{
    public partial class SchedulePage : Page
    {
        private int selectRow = -1;
        public SchedulePage()
        {
            InitializeComponent();
            update();
            Data.AutoGeneratedColumns += CollapsedColumns;
        }
        
        private void update()
        {
            NumberTextBox.Text = "";
            AuditoriumTextBox.Text = "";
            ScheduleViewTableAdapter g = new ScheduleViewTableAdapter();
            DataSet.ScheduleViewDataTable table = new DataSet.ScheduleViewDataTable();

            g.Fill(table);
            Data.ItemsSource = table;
            Data.SelectedIndex = selectRow < Data.Items.Count ? selectRow : -1;
            Buttons.selectItem(selectRow > -1 && selectRow < Data.Items.Count);
        }
        
        private void CollapsedColumns(object sender, EventArgs eventArgs)
        {
            Data.Columns[3].Visibility = Visibility.Collapsed;
            Data.Columns[4].Visibility = Visibility.Collapsed;
            Data.Columns[5].Visibility = Visibility.Collapsed;
        }

        private void ClickAdd(object sender)
        {
            if (!IsNumberGood())
            {
                this.showError("Указан неверный тип данных");
            }
            else if (this.IsFillArea())
            {
                new scheduleTableAdapter().Insert(Convert.ToInt32(NumberTextBox.Text), Convert.ToInt32(AuditoriumTextBox.Text), Convert.ToInt32(GroupComboBox.SelectedValue), Convert.ToInt32(TeacherComboBox.SelectedValue), Convert.ToInt32(LessonComboBox.SelectedValue), Date.Text);
                update();
            }
            else
            {
                this.showError("Заполнены не все поля");
            }
            
        }

        private void ClickChange(object sender)
        {
            if (!IsNumberGood())
            {
                this.showError("Указан неверный тип данных");
            }
            else if (this.IsFillArea())
            {
                new scheduleTableAdapter().Update(Convert.ToInt32(NumberTextBox.Text), Convert.ToInt32(AuditoriumTextBox.Text), Convert.ToInt32(GroupComboBox.SelectedValue), Convert.ToInt32(TeacherComboBox.SelectedValue), Convert.ToInt32(LessonComboBox.SelectedValue), Date.Text,
                        Convert.ToInt32((Data.SelectedItem as DataRowView).Row.ItemArray[0]), Convert.ToInt32((Data.SelectedItem as DataRowView).Row.ItemArray[1]), Convert.ToInt32((Data.SelectedItem as DataRowView).Row.ItemArray[2]), Convert.ToInt32((Data.SelectedItem as DataRowView).Row.ItemArray[3]), Convert.ToInt32((Data.SelectedItem as DataRowView).Row.ItemArray[4]), Convert.ToInt32((Data.SelectedItem as DataRowView).Row.ItemArray[5]));
                update();
            }
            else
            {
                this.showError("Заполнены не все поля");
            }
        }

        private void ClickDelete(object sender)
        {
            try
            {
                new scheduleTableAdapter().Delete(Convert.ToInt32((Data.SelectedItem as DataRowView).Row.ItemArray[0]), Convert.ToInt32((Data.SelectedItem as DataRowView).Row.ItemArray[1]), Convert.ToInt32((Data.SelectedItem as DataRowView).Row.ItemArray[2]), Convert.ToInt32((Data.SelectedItem as DataRowView).Row.ItemArray[3]), Convert.ToInt32((Data.SelectedItem as DataRowView).Row.ItemArray[4]), Convert.ToInt32((Data.SelectedItem as DataRowView).Row.ItemArray[5]));
                Buttons.selectItem(false);
                update();
            }
            catch (Exception exception)
            {
                this.showError("Нельзя удалить строчку");
            }

        }
        
        private void ClickCancel(object sender)
        {
            NumberTextBox.Text = "";
            AuditoriumTextBox.Text = "";
            this.selectRow = -1;
            Data.SelectedIndex = -1;
            Buttons.selectItem(false);
        }

        private void Doljnost_OnSelectionChanged(object sender, SelectionChangedEventArgs e)
        {
            if (Data.SelectedIndex > -1 && Data.SelectedIndex < Data.Items.Count)
            {
                selectRow = Data.SelectedIndex;
                var items = (Data.SelectedItem as DataRowView).Row;
                NumberTextBox.Text = items.ItemArray[1].ToString();
                AuditoriumTextBox.Text = items.ItemArray[2].ToString();
                GroupComboBox.SelectedValue = items.ItemArray[3];
                TeacherComboBox.SelectedValue = items.ItemArray[4];
                LessonComboBox.SelectedValue = items.ItemArray[5];
                Date.Text = items.ItemArray[6].ToString();

                Buttons.selectItem(true);
            }
        }

        private void showError(string text)
        {
            MessageBox.Show(text);
        }

        private bool IsFillArea()
        {
            return Methods.IsGoodString(NumberTextBox.Text) && Methods.IsGoodString(AuditoriumTextBox.Text) &&
                   Methods.IsGoodString(GroupComboBox.Text) && Methods.IsGoodString(TeacherComboBox.Text) &&
                   Methods.IsGoodString(LessonComboBox.Text) && Methods.IsGoodString(Date.Text);
        }
        
        private bool IsNumberGood()
        {
            return Methods.IsGoodInt(NumberTextBox.Text, 1, 5) && Methods.IsGoodInt(AuditoriumTextBox.Text, 100, 1000);
        }
    }
}