using System;
using System.Data;
using System.Windows;
using System.Windows.Controls;
using Practical.Data.DataSetTableAdapters;

using DataSet = Practical.Data.DataSet;

namespace Practical.TablesPage
{
    public partial class StudentPage : Page
    {
        private int selectRow = -1;
        
        public StudentPage()
        {
            InitializeComponent();
            update();
            Data.AutoGeneratedColumns += CollapsedColumns;
        }
        
        private void update()
        {
            PersonalComboBox.Text = "";
            ReceiptTextBox.Text = "";
            GroupComboBox.Text = "";
            StudentViewTableAdapter g = new StudentViewTableAdapter();
            DataSet.StudentViewDataTable table = new DataSet.StudentViewDataTable();

            g.Fill(table);
            Data.ItemsSource = table;
            Data.SelectedIndex = selectRow < Data.Items.Count ? selectRow : -1;
            Buttons.selectItem(selectRow > -1 && selectRow < Data.Items.Count);
        }
        
        private void CollapsedColumns(object sender, EventArgs eventArgs)
        {
            Data.Columns[1].Visibility = Visibility.Collapsed;
            Data.Columns[3].Visibility = Visibility.Collapsed;
        }

        private void ClickAdd(object sender)
        {
            if (!IsNumberGood())
            {
                this.showError("Указан неверный тип данных");
            }
            else if (this.IsFillArea())
            {
                new studentTableAdapter().Insert(Convert.ToInt32(PersonalComboBox.SelectedValue), Convert.ToInt32(ReceiptTextBox.Text), Convert.ToInt32(GroupComboBox.SelectedValue));
                update();
            }
            else
            {
                this.showError("Заполнены не все поля");
            }
        }

        private void ClickChange(object sender)
        {
            if (!IsNumberGood())
            {
                this.showError("Указан неверный тип данных");
            }
            else if (this.IsFillArea())
            {
                var items = (Data.SelectedItem as DataRowView).Row;
                new studentTableAdapter().Update(Convert.ToInt32(PersonalComboBox.SelectedValue), Convert.ToInt32(ReceiptTextBox.Text), Convert.ToInt32(GroupComboBox.SelectedValue), Convert.ToInt32(items.ItemArray[0]),
                        Convert.ToInt32(items.ItemArray[1]),Convert.ToInt32(items.ItemArray[2]),Convert.ToInt32(items.ItemArray[3]),Convert.ToInt32(items.ItemArray[0]));
                update();
            }
            else
            {
                this.showError("Заполнены не все поля");
            }
        }

        private void ClickDelete(object sender)
        {
            try
            {
                new studentTableAdapter().Delete(Convert.ToInt32((Data.SelectedItem as DataRowView).Row.ItemArray[0]), Convert.ToInt32(PersonalComboBox.SelectedValue), Convert.ToInt32(ReceiptTextBox.Text), Convert.ToInt32(GroupComboBox.SelectedValue));
                Buttons.selectItem(false);
                update();
            }
            catch (Exception exception)
            {
                this.showError("Нельзя удалить строчку");
            }

        }
        
        private void ClickCancel(object sender)
        {
            PersonalComboBox.Text = "";
            ReceiptTextBox.Text = "";
            GroupComboBox.Text = "";
            this.selectRow = -1;
            Data.SelectedIndex = -1;
            Buttons.selectItem(false);
        }

        private void Doljnost_OnSelectionChanged(object sender, SelectionChangedEventArgs e)
        {
            if (Data.SelectedIndex > -1 && Data.SelectedIndex < Data.Items.Count)
            {
                selectRow = Data.SelectedIndex;
                var items = (Data.SelectedItem as DataRowView).Row;
                PersonalComboBox.SelectedValue = items.ItemArray[1];
                ReceiptTextBox.Text = items.ItemArray[2].ToString();
                GroupComboBox.SelectedValue = items.ItemArray[3];
                Buttons.selectItem(true);
            }
        }

        private void showError(string text)
        {
            MessageBox.Show(text);
        }

        private bool IsFillArea()
        {
            return Methods.IsGoodString(PersonalComboBox.Text) && Methods.IsGoodString(ReceiptTextBox.Text) && Methods.IsGoodString(GroupComboBox.Text);
        }
        
        private bool IsNumberGood()
        {
            return Methods.IsGoodInt(ReceiptTextBox.Text, 2000, 3000);
        }
    }
}