using System;
using System.Data;
using System.Windows;
using System.Windows.Controls;
using Practical.Data.DataSetTableAdapters;

using DataSet = Practical.Data.DataSet;

namespace Practical.TablesPage
{
    public partial class WorkloadPage : Page
    {
        private int selectRow = -1;
        
        public WorkloadPage()
        {
            InitializeComponent();
            update();
            Data.AutoGeneratedColumns += CollapsedColumns;
        }
        
        private void update()
        {
            TeacherComboBox.Text = "";
            LessonComboBox.Text = "";
            WorkloadViewTableAdapter g = new WorkloadViewTableAdapter();
            DataSet.WorkloadViewDataTable table = new DataSet.WorkloadViewDataTable();

            g.Fill(table);
            Data.ItemsSource = table;
            Data.SelectedIndex = selectRow < Data.Items.Count ? selectRow : -1;
            Buttons.selectItem(selectRow > -1 && selectRow < Data.Items.Count);
        }

        private void CollapsedColumns(object sender, EventArgs eventArgs)
        {
            Data.Columns[1].Visibility = Visibility.Collapsed;
            Data.Columns[2].Visibility = Visibility.Collapsed;
        }
        
        private void ClickAdd(object sender)
        {
            try{
                if (this.IsFillArea())
                {
                    new workloadTableAdapter().Insert(Convert.ToInt32(TeacherComboBox.SelectedValue), Convert.ToInt32(LessonComboBox.SelectedValue));
                    update();
                }
                else
                {
                    this.showError("Заполнены не все поля");
                }
            }
            catch (Exception exception)
            {
                this.showError("Указан неверный тип данных");
            }
        }

        private void ClickChange(object sender)
        {
            try
            {
                if (this.IsFillArea())
                {
                    var items = (Data.SelectedItem as DataRowView).Row;
                    new workloadTableAdapter().Update(Convert.ToInt32(TeacherComboBox.SelectedValue), Convert.ToInt32(LessonComboBox.SelectedValue), Convert.ToInt32(items.ItemArray[0]), Convert.ToInt32(items.ItemArray[1]), Convert.ToInt32(items.ItemArray[2]));
                    update();
                }
                else
                {
                    this.showError("Заполнены не все поля");
                }
            }
            catch (Exception exception)
            {
                this.showError("Указан неверный тип данных");
            }
        }

        private void ClickDelete(object sender)
        {
            try
            {
                new workloadTableAdapter().Delete(Convert.ToInt32((Data.SelectedItem as DataRowView).Row.ItemArray[0]), Convert.ToInt32((Data.SelectedItem as DataRowView).Row.ItemArray[1]), Convert.ToInt32((Data.SelectedItem as DataRowView).Row.ItemArray[2]));
                Buttons.selectItem(false);
                update();
            }
            catch (Exception exception)
            {
                this.showError("Нельзя удалить строчку");
            }

        }
        
        private void ClickCancel(object sender)
        {
            TeacherComboBox.Text = "";
            LessonComboBox.Text = "";
            this.selectRow = -1;
            Data.SelectedIndex = -1;
            Buttons.selectItem(false);
        }

        private void Doljnost_OnSelectionChanged(object sender, SelectionChangedEventArgs e)
        {
            if (Data.SelectedIndex > -1 && Data.SelectedIndex < Data.Items.Count)
            {
                selectRow = Data.SelectedIndex;
                var items = (Data.SelectedItem as DataRowView).Row;
                TeacherComboBox.SelectedValue = items.ItemArray[1];
                LessonComboBox.SelectedValue = items.ItemArray[2];
                Buttons.selectItem(true);
            }
        }

        private void showError(string text)
        {
            MessageBox.Show(text);
        }

        private bool IsFillArea()
        {
            return Methods.IsGoodString(TeacherComboBox.Text) && Methods.IsGoodString(LessonComboBox.Text);
        }
    }
}